# -*- coding: utf-8 -*-
"""EB bill calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RVUZg4iQ6EIdHRmgP_rYewAMvhkNTRfH
"""

Number_of_units=int(input("Enter the amount of Electricity used (in units) : "))

if Number_of_units<=100:
  a=Number_of_units*0.50
  print("Your electricity consumption is",Number_of_units, "units and the bill is : ",a)
elif(Number_of_units>=101 and Number_of_units<=200):
  b=Number_of_units*1.50
  print("Your electricity consumption is",Number_of_units, "units and the bill is : ",b)
elif(Number_of_units>=201 and Number_of_units<=500):
  c=Number_of_units*2.50
  print("Your electricity consumption is",Number_of_units, "units and the bill is : ",c)
else:
  d=Number_of_units*3.50
  print("Your electricity consumption is",Number_of_units, "units and the bill is : ",d)