# -*- coding: utf-8 -*-
"""INTERNAL EXTERNAL PASS FAIL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lO81pBPlCEJx1u5OsvkioDHBT0vfKbEI
"""

internal_mark=int(input("Enter internal mark (o to 20): "))
external_mark=int(input("Enter external mark (0 to 80): "))


if (internal_mark>12 and internal_mark<=20) and (external_mark>40 and external_mark<=80):
  print("PASS OVERALL")
elif(internal_mark>20 and external_mark>80):
  print("Enter marks CORRECTLY")
else:
  print("FAIL")