# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nwjnet90cl6-_4VQAdh4HHlcmBFrhNmM
"""

l1=[1,2,3,4,5,6,7,8,9]

l1.index(1)
print(l1)
l1.index(2)
print(l1)
l1.index(3)
print(l1)
l1.append(8)
print(l1)

print(l1.count(8))

l2=[4,43,2,326,234,2,316,6,3,45,2,6]
l2.insert(0,100)

print(l2)

l1.clear()
print(l1)

l2.clear()
print(l2)