# -*- coding: utf-8 -*-
"""min mid max.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OUjbinpDG8_uG95frgAJr_u-n5R2T3Jy
"""

number_one=int(input("Enter first number: "))
number_two=int(input("Enter second number: "))
number_three=int(input("Enter third number: "))

if number_one<number_two and number_one<number_three:
  print([number_one,number_two,number_three])
elif(number_two<number_one and number_two<number_three):
  print([number_two,number_one,number_three])
elif(number_three<number_one and number_three<number_two):
  print([number_three,number_one,number_two])