# -*- coding: utf-8 -*-
"""sum of number from 1 to the given value.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16w0Yc4XaX5G3VQ-30lRLdPcSECqLJI1K
"""

def addition():
  number=int(input("Enter a number: "))
  z=0
  for i in range(1,number+1):
    z+=1
  print("The sum of values from 1 to",number,"is", z)

addition()