# -*- coding: utf-8 -*-
"""Voter eligibility.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16w0Yc4XaX5G3VQ-30lRLdPcSECqLJI1K
"""

def vote():
  age=int(input("Enter your age: "))
  state=str(input("Enter your state: "))
  phonenumber=int(input("Enter your phone number: "))
  aadharnumber=int(input("Enter your aadhar number: "))
  if (age>=18 and state=="tamilnadu") and (phonenumber>=6000000000 and phonenumber<=9999999999) and (aadharnumber>=111111111111 and aadharnumber<=999999999999):
    print("You are eligible to vote")
  else:
    ("You are not eligible to vote")

vote()